### ISSUE TITLE
App panics when react fails to fetch a dynamically imported module

### ISSUE THREAD

**Issue by circles-slave** [csesoc/Circles#785]
clicked on course bubble in progression checker 

Error
{"stack":"TypeError: Failed to fetch dynamically imported module: https://circles.csesoc.app/assets/index.db43b674.js","message":"Failed to fetch dynamically imported module: https://circles.csesoc.app/assets/index.db43b674.js"}

Error Info
at z1 (https://circles.csesoc.app/assets/vendor.caa8eec4.js:9:4367) at CS (https://circles.csesoc.app/assets/vendor.caa8eec4.js:9:6317) at V1 (https://circles.csesoc.app/assets/vendor.caa8eec4.js:9:5754) at RS (https://circles.csesoc.app/assets/vendor.caa8eec4.js:10:401) at u (https://circles.csesoc.app/assets/index.d0ac6755.js:8:73) at Suspense at TS (https://circles.csesoc.app/assets/vendor.caa8eec4.js:13:5051) at Ue (https://circles.csesoc.app/assets/index.9d1bb1eb.js:53:4027) at t (https://circles.csesoc.app/assets/vendor.caa8eec4.js:8:81935) at SS (https://circles.csesoc.app/assets/vendor.caa8eec4.js:8:67600)

**Comment by Peedee2002** [comment]
Ugh this suspense stuff is annoying, we need to try to set up better error boundaries or some retry mechanism for suspense

**Comment by Peedee2002** [comment]
We have addressed this as best we can, by fixing a dumb bug and allowing the user to not dump their data if they run into this issue.
